├── 00_create_tables.sql
├── 01_initial_analysis.sql
├── 02_standardization.sql
├── 03_inconsistencies.sql
├── 04_missing_values.sql
├── 05_duplicates.sql
├── 06_text_normalization.sql
├── 07_typo_detection.sql
├── 08_metadata.sql
└── 09_final_checks.sql